name: laravel_echo
description: Port of official Laravel Echo package for your Flutter apps.
version: 0.2.8
homepage: https://github.com/kakajansh/echo

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
